"""migrate tables

Revision ID: 2cbec106764a
Revises: 
Create Date: 2026-02-04 12:49:00.740451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbec106764a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('faculties',
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('f_id')
    )
    op.create_table('students',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('s_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('faculties')
    op.drop_table('courses')
    # ### end Alembic commands ###
