"""add foreign key in course

Revision ID: 3f03361b0305
Revises: 70cf45d27565
Create Date: 2026-02-04 13:09:19.797136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f03361b0305'
down_revision: Union[str, Sequence[str], None] = '70cf45d27565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'faculties', ['faculty_id'], ['f_id'])
    op.create_foreign_key(None, 'courses', 'students', ['student_id'], ['s_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'faculty_id')
    op.drop_column('courses', 'student_id')
    # ### end Alembic commands ###
