"""add association table and relationships

Revision ID: 580da81e939e
Revises: 26fface527c4
Create Date: 2026-02-10 17:17:24.421626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580da81e939e'
down_revision: Union[str, Sequence[str], None] = '26fface527c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.f_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.s_id'], ),
    sa.PrimaryKeyConstraint('association_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    # ### end Alembic commands ###
