"""add cascade in course

Revision ID: 5b0b5abf91a9
Revises: 6bea4e1b0e31
Create Date: 2026-02-11 16:09:01.608267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0b5abf91a9'
down_revision: Union[str, Sequence[str], None] = '6bea4e1b0e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('courses_student_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'students', ['student_id'], ['s_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_student_id_fkey'), 'courses', 'students', ['student_id'], ['s_id'])
    op.alter_column('courses', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
