"""add cascade

Revision ID: 6bea4e1b0e31
Revises: 3eae04ebf55a
Create Date: 2026-02-11 15:35:46.343854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bea4e1b0e31'
down_revision: Union[str, Sequence[str], None] = '3eae04ebf55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('association_table_student_id_fkey'), 'association_table', type_='foreignkey')
    op.drop_constraint(op.f('association_table_faculty_id_fkey'), 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'faculties', ['faculty_id'], ['f_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_table', 'students', ['student_id'], ['s_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key(op.f('association_table_faculty_id_fkey'), 'association_table', 'faculties', ['faculty_id'], ['f_id'])
    op.create_foreign_key(op.f('association_table_student_id_fkey'), 'association_table', 'students', ['student_id'], ['s_id'])
    # ### end Alembic commands ###
