"""add email field in student

Revision ID: 70cf45d27565
Revises: 2cbec106764a
Create Date: 2026-02-04 12:54:29.598389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cf45d27565'
down_revision: Union[str, Sequence[str], None] = '2cbec106764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('s_email', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 's_email')
    # ### end Alembic commands ###
