"""add UPDATE CASCADE

Revision ID: e93c22322a79
Revises: 5b0b5abf91a9
Create Date: 2026-02-11 16:55:23.898688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93c22322a79'
down_revision: Union[str, Sequence[str], None] = '5b0b5abf91a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('association_table_faculty_id_fkey'), 'association_table', type_='foreignkey')
    op.drop_constraint(op.f('association_table_student_id_fkey'), 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'students', ['student_id'], ['s_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'association_table', 'faculties', ['faculty_id'], ['f_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('courses_student_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'students', ['student_id'], ['s_id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_student_id_fkey'), 'courses', 'students', ['student_id'], ['s_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key(op.f('association_table_student_id_fkey'), 'association_table', 'students', ['student_id'], ['s_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('association_table_faculty_id_fkey'), 'association_table', 'faculties', ['faculty_id'], ['f_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
